# (c) mike.maggire 2017
# Créé à partir de maggire jekyll fast-start template

# Configuration des variables pour génerer le site dans une version prête à être déployée un serveur de test
JEKYLL_ENV: test
strict_front_matter: true
destination: _site_ready2deploy
url: http://bigmama/web_acceptance/blogging-studio-jekyll
baseurl: /web_acceptance/blogging-studio-jekyll

include:
 - _pages
 - .htaccess
 - openurl.bat
