#
# (c) mike.maggire 2017
#
# Pour les règles syntaxiques à respecter dans ce fichier : https://fr.wikipedia.org/wiki/YAML 

# Configuration initiale
title: Blogging StudioJekyll
tagline: Suivez le guide
description: Guides pour creer rapidement des sites web sécurisés et performants avec Jekyll et Visual Studio sous Windows.

# References de l'auteur du site
# Seul le nom est obligatoire
# Les id sont utilisés pour faire apparaitre mes boutons réseaux sociaux sur le site
author:
  name: Mike Maggire
  url: https://twitter.com/mikemaggire
  email: mike.maggire@gmail.com
  twitter_id: mikemaggire
  github_id:  mikemaggire
  #gplus_id: +mikemaggire
  #facebook_id: mikemaggire
  #linkedin_id: mikemaggire

# paramètres spécifique à ce site
collections:
  guide: 
    output: true
    permalink: /:collection/:title.html
  pages:
    output: true

############################################################ VERSION
# NOTA : Le numéro de version V:x.y.z du site est géré automatiquement 
# au moment du deploiement en test et en prod
# Le numéro z est incrémenté à chaque build de l'environnement de test
# Le numéro y est incrémenté à chaque build de l'environnement de prod
# Pour incrémenter le numéro de version majeur (x), utilisez la commande
# 'npm version major' en ouvrant une console au niveau du repertoire racine de votre sire

############################################################ COMMENTAIRES
# Pour activer DISQUS à la fin des articles 
# renseignez votre identifiant DISQUS (voir https://disqus.com/) 
# en face de la variable 'shortname' ci-après.
# Plus d'explications : http://wiki.maggire.net/blogging-studio-jekyll/2017/06/25/comment-activer-commentaires.html
# Pour désactiver DISQUS, mettez les deux lignes suivantes en commentaire
disqus:
  shortname: blogging-studio-jekyll

############################################################ ANALYTICS
# Pour activer Google Analytics sur vos pages
# Sinon mettez cette ligne en commentaire
google_analytics: UA-23118933-9

############################################################
# Les variables suivantes ne sont pas à modifier
############################################################

# encoding & format
# se référer à http://shopify.github.io/liquid/filters/date/ pour personnaliser le format de date
encoding: utf-8
lang: fr
date_format: "%d/%m/%Y"
timezone: Europe/Paris
markdown: kramdown

# Produces a cleaner folder structure when using categories
permalink: /blog/:categories/:title.html

# Extension utilisées
plugins: 
 - jekyll-feed
 - jemoji
 - jekyll-sitemap

# Exclusions spécifiques à VS
# Ces fichiers ne seront pas générés dans le repertoire de destination _site ou _site2deploy
exclude: 
 - LICENSE.txt
 - TODO.md
 - README.md
 - package.json
 - bs-config.json
 - deploy2prod.bat
 - deploy2test.bat
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/

# Nous forcons le traitement de .htaccess
include: 
  - .htaccess
#  - _pages

#kramdown:
#  auto_ids:       true
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo
#  input:          GFM
#  hard_wrap:      false
#  footnote_nr:    1
