# (c) mike.maggire 2017
# Créé à partir de maggire jekyll fast-start template

# Configuration initiale
title: Blogging StudioJekyll
tagline: Guides pas à pas pour publier sur vos serveurs en quelques minutes.
description: Guides pour creer rapidement des sites web performants et funs avec Jekyll et Visual Studio.

# References de l'auteur
# Seul le nom est obligatoire
author:
  name: Mike Maggire
  url: https://twitter.com/mikemaggire
  email: mike.maggire@gmail.com
  twitter_username: mikemaggire
  github_username:  mike.maggire

# Le numéro de version du site, à incrémenter au moment des publications
version: 0.1.2

# Pour activer la gestion des commentaires à la fin des articles 
# Vous devez renseigner votre id disqus (voir https://disqus.com/)
# Sinon mettez ces deux lignes en commentaire
disqus:
  shortname: blogging-studio-jekyll

########################
# Les variables suivantes ne sont pas à modifier
########################

# encoding & format
# se référer à http://shopify.github.io/liquid/filters/date/ pour personnaliser le format de date
encoding: utf-8
lang: fr
date_format: "%d/%m/%Y"
timezone: Europe/Paris
markdown: kramdown

# Extension utilisées
plugins: 
 - jekyll-feed
 - emoji_for_jekyll
 - jekyll-sitemap

# Exclusions spécifiques à VS
# Ces fichiers ne seront pas générés dans le repertoire de destination _site ou _site2deploy
exclude: 
 - LICENSE.txt
 - TODO.md
 - README.md
 - package.json
 - bs-config.json
 - deploy2prod.bat
 - deploy2test.bat
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/

# Par commodité, nous stockons les sources des pages dans le repertoire '_pages'
# Nous forcons le traitement de .htaccess
# A noter que la page index.md doit elle rester à la racine du site   
include: 
 - _pages
 - .htaccess

#kramdown:
#  auto_ids:       true
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo
#  input:          GFM
#  hard_wrap:      false
#  footnote_nr:    1
